version: '3'

services:
  pqai_snippet:
    image: pqai_snippet
    container_name: pqai_snippet
    build: .
    volumes:
      - type: bind
        source: ./assets
        target: /app/assets
    restart: always
    ports:
      - ${PORT}:80
    environment:
      - PORT=${PORT}
      - RERANKING_SRV_ENDPOINT=${RERANKING_SRV_ENDPOINT}
      - ENCODER_SRV_ENDPOINT=${ENCODER_SRV_ENDPOINT}
